try both open and launching the binary with full path inside .app

diff --git a/.github/workflows/0.21.0plus6 Test installer script.yml b/.github/workflows/0.21.0plus6 Test installer script.yml
--- a/.github/workflows/0.21.0plus6 Test installer script.yml
+++ b/.github/workflows/0.21.0plus6 Test installer script.yml
@@ -59,8 +59,14 @@ jobs:
             exit 1
           fi
 
-      - name: Run OpenSpace for 5 minutes with -b bypasslauncher
+      - name: Run OpenSpace for 5 minutes
         run: | 
-          open $HOME/OpenSpace/bin/OpenSpace.app -b || echo "Allow errors due to headless runner."
+          open $HOME/OpenSpace/bin/OpenSpace.app || echo "Allow errors due to headless runner."
+          sleep 300
+
+      - name: Run OpenSpace for 5 minutes from executable with -b
+        run: |
+          cd $HOME/OpenSpace
+          ./bin/OpenSpace.app/Contents/MacOS/OpenSpace -b || echo "Allow errors due to headless runner."
           sleep 300
 
